import xmlrpc.client
proxy = xmlrpc.client.Server("http://localhost:9999")
num1=int(input(" Enter num1 : "))
num2=int(input("  Enter num2 : "))
result1=proxy.mod(num1,num2)
result2=proxy.add(num1,num2)
result3=proxy.sub(num1,num2)
result4=proxy.mul(num1,num2)
result5=proxy.div(num1,num2)
print(f"Result is: {result1}")
print(f"Addition is: {result2}")
print(f"Substraction is: {result3}")
print(f"Multiplication is: {result4}")
print(f"Division is: {result5}")
